services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: ./pyproject.toml

  database:
    image: postgres:17
    volumes:
      - ./.data/db:/var/lib/postgresql/data/
    env_file: 
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
