services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: ./pyproject.toml
